export type Tool = {
  id: number;
  name: string;
  url: string;
  logo: string;
  meta: string;
};

export const tools: Tool[] = [
  {
    id: 1,
    name: "Screaming Frog",
    url: "https://www.screamingfrog.co.uk/seo-spider/",
    logo: "https://cdn.worldvectorlogo.com/logos/screaming-frog.svg",
    meta: "Technical SEO Crawler",
  },
  {
    id: 2,
    name: "Sitebulb",
    url: "https://sitebulb.com",
    logo: "https://sitebulb.com/assets/images/sitebulb-logo.svg",
    meta: "Technical Audit",
  },
  {
    id: 3,
    name: "DeepCrawl",
    url: "https://www.lumar.io/",
    logo: "https://www.lumar.io/wp-content/uploads/2022/11/lumar-logo.svg",
    meta: "Enterprise Audit",
  },
  {
    id: 4,
    name: "Ahrefs Site Audit",
    url: "https://ahrefs.com/site-audit",
    logo: "https://cdn.worldvectorlogo.com/logos/ahrefs.svg",
    meta: "Site Audits",
  },
  {
    id: 5,
    name: "SEMrush Site Audit",
    url: "https://www.semrush.com/siteaudit/",
    logo: "https://cdn.worldvectorlogo.com/logos/semrush.svg",
    meta: "Site Audit",
  },
  {
    id: 6,
    name: "Google Search Console",
    url: "https://search.google.com/search-console",
    logo: "https://www.gstatic.com/images/branding/product/1x/search_console_48dp.png",
    meta: "Index & Errors",
  },
  {
    id: 7,
    name: "SiteGuru",
    url: "https://siteguru.co/",
    logo: "https://siteguru.co/wp-content/themes/siteguru/assets/images/logo.svg",
    meta: "SEO Monitoring",
  },
  {
    id: 8,
    name: "Seona AI",
    url: "https://seona.ai/",
    logo: "https://seona.ai/favicon.ico",
    meta: "AI SEO Manager",
  },
  {
    id: 9,
    name: "Diib",
    url: "https://www.diib.com",
    logo: "https://www.diib.com/wp-content/uploads/2021/06/Diib-Logo-Blue.svg",
    meta: "Site Insights",
  },
  {
    id: 10,
    name: "Superflow",
    url: "https://superflow.ai/",
    logo: "https://superflow.ai/logo.png",
    meta: "SEO Feedback",
  },
  {
    id: 11,
    name: "Ahrefs Keywords Explorer",
    url: "https://ahrefs.com/keywords-explorer",
    logo: "https://cdn.worldvectorlogo.com/logos/ahrefs.svg",
    meta: "Keyword Research",
  },
  {
    id: 12,
    name: "SEMrush Keyword Magic",
    url: "https://www.semrush.com/features/keyword-research/",
    logo: "https://cdn.worldvectorlogo.com/logos/semrush.svg",
    meta: "Keyword Research",
  },
  {
    id: 13,
    name: "Google Keyword Planner",
    url: "https://ads.google.com/home/tools/keyword-planner/",
    logo: "https://www.gstatic.com/images/branding/product/1x/ads_48dp.png",
    meta: "Search Volumes",
  },
  {
    id: 14,
    name: "Ubersuggest",
    url: "https://neilpatel.com/ubersuggest/",
    logo: "https://cdn.worldvectorlogo.com/logos/ubersuggest.svg",
    meta: "Keyword Ideas",
  },
  {
    id: 15,
    name: "KeywordTool.io",
    url: "https://keywordtool.io",
    logo: "https://keywordtool.io/images/kt-logo.png",
    meta: "Long-tail Keywords",
  },
  {
    id: 16,
    name: "AnswerThePublic",
    url: "https://answerthepublic.com",
    logo: "https://answerthepublic.com/favicon.ico",
    meta: "Search Questions",
  },
  {
    id: 17,
    name: "Thruu",
    url: "https://thruu.co/",
    logo: "https://thruu.co/wp-content/uploads/2022/05/thruu-logo.svg",
    meta: "SERP Analyzer",
  },
  {
    id: 18,
    name: "AlsoAsked",
    url: "https://alsoasked.com/",
    logo: "https://alsoasked.com/apple-touch-icon.png",
    meta: "Question Mining",
  },
  {
    id: 19,
    name: "Komo.ai",
    url: "https://komo.ai/",
    logo: "https://komo.ai/favicon.ico",
    meta: "AI Search",
  },
  {
    id: 20,
    name: "Ahrefs Backlink Checker",
    url: "https://ahrefs.com/backlink-checker",
    logo: "https://cdn.worldvectorlogo.com/logos/ahrefs.svg",
    meta: "Backlink Analysis",
  },
  {
    id: 21,
    name: "Majestic",
    url: "https://majestic.com",
    logo: "https://majestic.com/assets/images/global/brand-assets/logo-dark.svg",
    meta: "Link Intelligence",
  },
  {
    id: 22,
    name: "SEMrush Backlinks",
    url: "https://www.semrush.com/analytics/backlinks/",
    logo: "https://cdn.worldvectorlogo.com/logos/semrush.svg",
    meta: "Backlink Data",
  },
  {
    id: 23,
    name: "Moz Link Explorer",
    url: "https://moz.com/link-explorer",
    logo: "https://cdn.worldvectorlogo.com/logos/moz.svg",
    meta: "Link Research",
  },
  {
    id: 24,
    name: "Monitor Backlinks",
    url: "https://monitorbacklinks.com",
    logo: "https://monitorbacklinks.com/assets/img/logo.svg",
    meta: "Backlink Tracker",
  },
  {
    id: 25,
    name: "Linkody",
    url: "https://linkody.com",
    logo: "https://linkody.com/images/linkody-logo.svg",
    meta: "Backlink Monitoring",
  },
  {
    id: 26,
    name: "IndexMeNow",
    url: "https://indexmenow.com/",
    logo: "https://indexmenow.com/favicon.ico",
    meta: "Indexing Service",
  },
  {
    id: 27,
    name: "Express Indexer",
    url: "https://expressindexer.com/",
    logo: "https://expressindexer.com/favicon.ico",
    meta: "Index URLs",
  },
  {
    id: 28,
    name: "OneHourIndexing",
    url: "https://onehourindexing.com/",
    logo: "https://onehourindexing.com/favicon.ico",
    meta: "Indexing Service",
  },
  {
    id: 29,
    name: "InstantLinkIndexer",
    url: "https://instantlinkindexer.com/",
    logo: "https://instantlinkindexer.com/favicon.ico",
    meta: "Fast Indexing",
  },
  {
    id: 30,
    name: "Lindexed",
    url: "https://lindexed.com/",
    logo: "https://lindexed.com/favicon.ico",
    meta: "Link Indexing",
  },
  {
    id: 31,
    name: "GSC URL Submit",
    url: "https://search.google.com/search-console",
    logo: "https://www.gstatic.com/images/branding/product/1x/search_console_48dp.png",
    meta: "Manual Submit",
  },
  {
    id: 32,
    name: "Ping-o-Matic",
    url: "https://pingomatic.com/",
    logo: "https://pingomatic.com/favicon.ico",
    meta: "Ping Services",
  },
  {
    id: 33,
    name: "Pingler",
    url: "https://pingler.com/",
    logo: "https://pingler.com/favicon.ico",
    meta: "Ping Tool",
  },
  {
    id: 34,
    name: "PubSubHubbub",
    url: "https://pubsubhubbub.appspot.com/",
    logo: "https://pubsubhubbub.appspot.com/favicon.ico",
    meta: "Pub/Sub Ping",
  },
  {
    id: 35,
    name: "Index Kings",
    url: "https://indexkings.com/",
    logo: "https://indexkings.com/favicon.ico",
    meta: "URL Indexing",
  },
  {
    id: 36,
    name: "Small SEO Tools Ping",
    url: "https://smallseotools.com/ping-site/",
    logo: "https://smallseotools.com/assets/images/favicon.png",
    meta: "Bulk Ping",
  },
  {
    id: 37,
    name: "ChatGPT",
    url: "https://chat.openai.com",
    logo: "https://upload.wikimedia.org/wikipedia/commons/0/04/OpenAI_Logo.svg",
    meta: "AI Content",
  },
  {
    id: 38,
    name: "Jasper AI",
    url: "https://www.jasper.ai",
    logo: "https://www.jasper.ai/assets/images/logo.svg",
    meta: "AI Writing",
  },
  {
    id: 39,
    name: "NeuronWriter",
    url: "https://neuronwriter.com",
    logo: "https://neuronwriter.com/uploads/1/4/6/8/146887114/neuronwriter-logo.png",
    meta: "Content Optimization",
  },
  {
    id: 40,
    name: "Surfer SEO",
    url: "https://surferseo.com",
    logo: "https://cdn.worldvectorlogo.com/logos/surfer.svg",
    meta: "Content Optimization",
  },
  {
    id: 41,
    name: "Writesonic",
    url: "https://writesonic.com",
    logo: "https://writesonic.com/favicon.ico",
    meta: "AI Writing",
  },
  {
    id: 42,
    name: "Koala Writer",
    url: "https://koala.ai/",
    logo: "https://koala.ai/favicon.ico",
    meta: "AI Writing",
  },
  {
    id: 43,
    name: "Frase.io",
    url: "https://frase.io",
    logo: "https://frase.io/assets/img/logo.svg",
    meta: "Content Research",
  },
  {
    id: 44,
    name: "Cora SEO",
    url: "https://www.getcora.com/",
    logo: "https://www.getcora.com/wp-content/uploads/2020/06/cora-logo.png",
    meta: "SERP Testing",
  },
  {
    id: 45,
    name: "PageOptimizer Pro",
    url: "https://pageoptimizer.pro/",
    logo: "https://pageoptimizer.pro/images/pop-logo.svg",
    meta: "On-page Testing",
  },
  {
    id: 46,
    name: "BrightLocal",
    url: "https://www.brightlocal.com",
    logo: "https://www.brightlocal.com/wp-content/uploads/2021/06/bl-logo.svg",
    meta: "Local SEO",
  },
  {
    id: 47,
    name: "Whitespark",
    url: "https://www.whitespark.ca/",
    logo: "https://www.whitespark.ca/images/white-spark-logo.svg",
    meta: "Local Citations",
  },
  {
    id: 48,
    name: "Moz Local",
    url: "https://moz.com/products/local",
    logo: "https://cdn.worldvectorlogo.com/logos/moz.svg",
    meta: "Local Listings",
  },
  {
    id: 49,
    name: "Google Business Profile",
    url: "https://business.google.com/",
    logo: "https://www.gstatic.com/images/branding/product/1x/maps_48dp.png",
    meta: "Business Manager",
  },
  {
    id: 50,
    name: "Local Falcon",
    url: "https://localfalcon.com/",
    logo: "https://localfalcon.com/favicon.ico",
    meta: "Local Rank Tracking",
  },
  {
    id: 51,
    name: "Perplexity AI",
    url: "https://www.perplexity.ai/",
    logo: "https://www.perplexity.ai/favicon.ico",
    meta: "AI Search",
  },
];
